import { describe, expect, it } from "vitest";
import { analyzeContent } from "./analyze";
describe("analyzeContent",()=>{
  it("counts content signals",()=>{const result=analyzeContent("A clear hook! What do you think? #writing @postlens https://example.com");expect(result.wordCount).toBe(10);expect(result.questions).toBe(1);expect(result.hashtags).toBe(1);expect(result.mentions).toBe(1);expect(result.links).toBe(1);});
  it("recommends a CTA when one is absent",()=>{const result=analyzeContent("A short statement about a useful idea.");expect(result.recommendations.some(r=>r.category==="CTA")).toBe(true);});
  it("handles empty input",()=>{const result=analyzeContent("");expect(result.wordCount).toBe(0);expect(result.overallScore).toBe(0);});
  it("returns real evidence ranges for a weak hook and missing CTA",()=>{const text="A long opening that explains a useful idea in a calm way before getting to the point. It may help readers understand the context.";const result=analyzeContent(text);const hook=result.findings.find(f=>f.id==="hook-opening");const cta=result.findings.find(f=>f.id==="cta-missing");expect(hook?.originalText).toBe(text.slice(hook?.startIndex,hook?.endIndex));expect(cta?.startIndex).toBe(text.length);expect(cta?.endIndex).toBe(text.length);});
  it("keeps hashtag fixes within valid text ranges",()=>{const text="A post #one #two #three #four #five #six #seven";const result=analyzeContent(text);const finding=result.findings.find(f=>f.id==="hashtag-set");expect(finding?.canApplyFix).toBe(true);expect(text.slice(finding!.startIndex, finding!.endIndex)).toBe(finding!.originalText);});
  it("supports multiple and overlapping findings without invalid ranges",()=>{const text="This opening spends a very long time explaining a useful idea with extra context that readers may not need before they reach the point. It continues here.";const result=analyzeContent(text);expect(result.findings.length).toBeGreaterThanOrEqual(2);expect(result.findings.some(f=>f.id==="hook-opening"&&f.startIndex===0)).toBe(true);expect(result.findings.every(f=>(f.startIndex??0)>=0&&(f.endIndex??0)<=text.length)).toBe(true);});
  it("handles punctuation, emoji and special characters",()=>{const result=analyzeContent("“Build less, learn more” — a useful idea ✨ #focus");expect(result.characterCount).toBeGreaterThan(0);expect(result.hashtags).toBe(1);});
});
